server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api.movie.app

  devtools:
    restart:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations: classpath:db/migration

  freemarker:
    template-loader-path:
      - classpath:/templates
    suffix: .ftlh

  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
        keep-alive: "60s"
        thread-name-prefix: mail-async-

tmdb:
  base-url: ${TMDB_BASE_URL}
  api-key: ${TMDB_API_KEY}

jwt:
  access-token-key: ${JWT_ACCESS_TOKEN_KEY}
  refresh-token-key: ${JWT_REFRESH_TOKEN_KEY}
  access-token-live-time: 15
  refresh-token-live-time: 7

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USER}
  app-pass: ${GMAIL_APP_PASS}
  auth: true
  start-tls: true