version: 2.1

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build \
              -t ${DOCKERHUB_USERNAME}/movie-v2-be:${CIRCLE_SHA1} \
              -t ${DOCKERHUB_USERNAME}/movie-v2-be:latest \
              .

      - run:
          name: Login to Docker Hub
          command: |
            echo "${DOCKERHUB_ACCESS_TOKEN}" | docker login \
              -u "${DOCKERHUB_USERNAME}" \
              --password-stdin

      - run:
          name: Push Docker image
          command: |
            docker push ${DOCKERHUB_USERNAME}/movie-v2-be:${CIRCLE_SHA1}
            docker push ${DOCKERHUB_USERNAME}/movie-v2-be:latest

      - add_ssh_keys:
          fingerprints:
            - "SHA256:iTOCamk8NuBTC+80zyasKwTAIdIXhJZEwydbVj2VEgA"

      - run:
          name: Deploy backend to EC2
          command: |
            ssh -o StrictHostKeyChecking=no \
              -o PubkeyAcceptedKeyTypes=+ssh-rsa \
              ${EC2_USER}@${EC2_HOST} "
                cd /home/ubuntu &&
                sed -i 's/^BACKEND_TAG=.*/BACKEND_TAG=${CIRCLE_SHA1}/' .env &&
                sudo docker compose pull backend &&
                sudo docker compose up -d backend &&
                sudo docker image prune -a -f &&
                sudo docker system prune -af
              "

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main